- hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pull Docker Image
      command: docker pull parvg/scientific-calculator

    - name: Stop Existing Containers
      command: docker stop sci-calc || true
      ignore_errors: true

    - name: Remove existing Containers
      command: docker rm sci-calc || true
      ignore_errors: true

    - name: Run Container
      command: docker run -d --name sci-calc -p 8000:8000 parvg/scientific-calculator
